import { getCssText } from "@admin/styles";
import { globalStyles } from "@admin/styles/global";
import { Roboto, Bungee } from "next/font/google";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const robotFont = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
});
const bungeeFont = Bungee({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bungee",
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${robotFont.variable} ${bungeeFont.variable}`}>
      <body>
        {children}
        <style
          dangerouslySetInnerHTML={{
            __html: `${getCssText()} ${globalStyles()}`,
          }}
        />
      </body>
    </html>
  );
}
